name: Update Ad Rules

permissions:
  contents: write
  
on:
  schedule:
    - cron: "0 7 8-14,22-28 * 1"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Build adguardhome rule
      run: |
        npm install -g @adguard/hostlist-compiler
        hostlist-compiler -c source.json -o rule/adblock.txt

    - name: Build smartdns rule
      run: |
        python3 ./smartdns-ad.py
        python3 ./smartdns-ad-white.py

    - name: Set tag
      run: echo "TAG_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Update Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        files: |
          ./rule/adblock.txt
          ./rule/smartdns-ad.txt
          ./rule/smartdns-ad-white.txt
